const languageData = {
  en: {
    title: "ThermaTrace",
    navHome: "Home",
    navAbout: "About",
    navFeatures: "Features",
    navPricing: "Pricing",
    navTeam: "Team",
    homeTitle: "Ensure Safe & Compliant Medicine Storage with Real Time - Monitoring",
    homeDesc: "ThermaTrace provides cutting-edge cold chain monitoring solutions to ensure pharmaceutical integrity throughout the supply chain with 24/7 real-time temperature tracking and compliance reporting.",
    requestDemo: "Request a Demo",
    learnMore: "Learn More",
    aboutBtn: "About ThermaTrace",
    aboutTitle: "Ensuring Pharmaceutical Safety Through Innovation",
    aboutDesc1: "ThermaTrace revolutionizes medicine storage monitoring by providing real-time temperature tracking and compliance reporting, ensuring the integrity of temperature-sensitive medications from pharmacy to patient.",
    aboutDesc2: "Our mission is to safeguard pharmaceutical products by delivering enterprise-grade cold chain monitoring solutions that are accessible, reliable, and easy to implement for healthcare facilities of all sizes.",
    aboutDesc3: "With ThermaTrace, healthcare providers can maintain regulatory compliance, reduce medication waste, and most importantly, ensure patient safety through continuous temperature monitoring and instant alert systems.",
    featuresBtn: "Our Features",
    featuresTitle: "Complete Cold Chain Monitoring Solution",
    featuresSubtitle: "Advanced features designed to ensure medication safety, regulatory compliance, and operational excellence for healthcare providers.",
    featureAlerts: "Real time - Alerts",
    featureAlertsDesc: "Instant notifications via email when temperature thresholds are breached.",
    featureHistory: "Temperature History",
    featureHistoryDesc: "Comprehensive historical data tracking with detailed analytics and trend visualization.",
    featureCompliance: "Compliance Reports",
    featureComplianceDesc: "Automated regulatory compliance reports that meet pharmaceutical industry standards.",
    featureWeb: "Web Application Access",
    featureWebDesc: "Secure Web Application platform accessible from any device, anywhere in the world.",
    ctaTitle: "Ready to secure your medicine Storage?",
    ctaDesc: "Join healthcare providers worldwide who trust ThermaTrace for their cold chain monitoring needs.",
    pricingBtn: "Platform Pricing",
    pricingTitle: "Choose the Perfect Plan for Your Facility",
    pricingDesc: "Flexible pricing options designed to scale with healthcare providers of all sizes, from small clinics to large hospital networks.",
    freemiumTitle: "Freemium",
    freemiumDesc: "Perfect for small clinics getting started",
    freemiumPrice: "$0 /month",
    freemiumFeature1: "Up to 2 temperatures monitoring points",
    freemiumFeature2: "Web dashboard access",
    freemiumFeature3: "7-day data history",
    freemiumFeature4: "Basic Email alerts",
    freemiumFeature5: "Community support",
    premiumTitle: "Premium",
    premiumDesc: "Ideal for pharmacies and medical centers",
    premiumPrice: "$60 /month",
    premiumFeature1: "Up to 15 temperature monitoring points",
    premiumFeature2: "Real-time email alerts",
    premiumFeature3: "Detailed compliance reports",
    premiumFeature4: "Multi-user access",
    premiumFeature5: "Custom alerts",
    premiumFeature6: "Data export capabilities",
    premiumFeature7: "Priority support",
    enterpriseTitle: "Enterprise",
    enterpriseDesc: "Scalable solutions for hospital networks or laboratories",
    enterprisePrice: "Custom",
    enterpriseFeature1: "Unlimited monitoring points",
    enterpriseFeature2: "Advanced analytics & insights",
    enterpriseFeature3: "Custom integrations & API access",
    enterpriseFeature4: "Priority Support",
    enterpriseFeature5: "Advanced user permissions",
    enterpriseFeature6: "Custom training & onboarding",
    enterpriseFeature7: "SLA Guarantees",
    getStarted: "Get Started",
    contactUs: "Contact Us",
    pricingFooter1: "All plans include secure cloud storage, GDPR compliance, and regular platform updates",
    pricingFooter2: "For custom solutions please Contact us for enterprise pricing.",
    teamBtn: "Meet our Team",
    teamMember1: "Fabrizio Panta",
    teamMember2: "Axel Ordoñez",
    teamMember3: "Jean Grandez",
    teamMember4: "Oscar Espinoza",
    teamMember5: "Frezzia Espinoza",
    teamRole: "Software Engineer",
    teamDesc: "Tech enthusiast, and Web developer",
    tryDemo: "Try Demo",
    footerTagline: "Leading the revolution in pharmaceutical cold chain monitoring. Ensuring medicine safety through innovative technology.",
    faqTitle: "Frequently Asked Questions",
    faqInstallTitle: "How easy is it to install ThermaTrace?",
    faqInstallDesc: "ThermaTrace can be installed in under 30 minutes. Our team provides complete setup assistance and training for your staff.",
    faqComplianceTitle: "Does it meet regulatory compliance standards?",
    faqComplianceDesc: "Yes, ThermaTrace meets FDA, WHO, and other international pharmaceutical storage compliance requirements with automated reporting.",
    faqSupportTitle: "What kind of support do you provide?",
    faqSupportDesc: "We offer 24/7 technical support, regular system updates, and dedicated account management for enterprise clients.",
    faqIntegrationTitle: "Can it integrate with existing systems?",
    faqIntegrationDesc: "ThermaTrace integrates seamlessly with most pharmacy management systems, EHRs, and hospital information systems.",
    faqCostTitle: "What are the pricing options?",
    faqCostDesc: "We offer flexible pricing plans for small clinics to large hospital networks, with no long-term contracts required.",
    faqDataTitle: "How is my data protected?",
    faqDataDesc: "All data is encrypted and stored securely in HIPAA-compliant cloud infrastructure with regular security audits.",
    footerLogo: "ThermaTrace",
    footerDistrictTitle: "Locations",
    footerDistrict: "New York\nSan Francisco\nBoston",
    footerFollowTitle: "Follow Us",
    footerHours: "Technical Support: 24/7 | Sales: Monday-Friday 9am-6pm EST",
    footerContactTitle: "Contact",
    footerContact: "Email: contact@thermatrace.com, Phone: +1 (555) THERMA, Support: support@thermatrace.com",
    footerCopyright: "© ThermaTrace Inc. © 2025. All Rights Reserved."
  },
  es: {
    title: "ThermaTrace",
    navHome: "Inicio",
    navAbout: "Acerca de",
    navFeatures: "Características",
    navPricing: "Precios",
    navTeam: "Equipo",
    homeTitle: "Asegure el Almacenamiento Seguro y Cumplimiento de Medicamentos con Monitoreo en Tiempo Real",
    homeDesc: "ThermaTrace proporciona soluciones de monitoreo de cadena de frío de vanguardia para asegurar la integridad farmacéutica a lo largo de la cadena de suministro con seguimiento de temperatura en tiempo real 24/7 e informes de cumplimiento.",
    requestDemo: "Solicitar Demo",
    learnMore: "Saber Más",
    aboutBtn: "Acerca de ThermaTrace",
    aboutTitle: "Asegurando la Seguridad Farmacéutica a través de la Innovación",
    aboutDesc1: "ThermaTrace revoluciona el monitoreo del almacenamiento de medicamentos al proporcionar seguimiento de temperatura en tiempo real e informes de cumplimiento, asegurando la integridad de medicamentos sensibles a la temperatura desde la farmacia hasta el paciente.",
    aboutDesc2: "Nuestra misión es salvaguardar los productos farmacéuticos al entregar soluciones de monitoreo de cadena de frío de nivel empresarial que son accesibles, confiables y fáciles de implementar para instalaciones de atención médica de todos los tamaños.",
    aboutDesc3: "Con ThermaTrace, los proveedores de atención médica pueden mantener el cumplimiento regulatorio, reducir el desperdicio de medicamentos y, lo más importante, asegurar la seguridad del paciente a través del monitoreo continuo de temperatura y sistemas de alerta instantánea.",
    featuresBtn: "Nuestras Características",
    featuresTitle: "Solución Completa de Monitoreo de Cadena de Frío",
    featuresSubtitle: "Características avanzadas diseñadas para asegurar la seguridad de medicamentos, cumplimiento regulatorio y excelencia operativa para proveedores de atención médica.",
    featureAlerts: "Alertas en Tiempo Real",
    featureAlertsDesc: "Notificaciones instantáneas por correo electrónico cuando se violan los umbrales de temperatura.",
    featureHistory: "Historial de Temperatura",
    featureHistoryDesc: "Seguimiento integral de datos históricos con análisis detallados y visualización de tendencias.",
    featureCompliance: "Informes de Cumplimiento",
    featureComplianceDesc: "Informes automatizados de cumplimiento regulatorio que cumplen con los estándares de la industria farmacéutica.",
    featureWeb: "Acceso a Aplicación Web",
    featureWebDesc: "Plataforma de Aplicación Web segura accesible desde cualquier dispositivo, en cualquier parte del mundo.",
    ctaTitle: "¿Listo para asegurar tu Almacenamiento de Medicamentos?",
    ctaDesc: "Únete a proveedores de atención médica en todo el mundo que confían en ThermaTrace para sus necesidades de monitoreo de cadena de frío.",
    pricingBtn: "Precios de Plataforma",
    pricingTitle: "Elige el Plan Perfecto para tu Instalación",
    pricingDesc: "Opciones de precios flexibles diseñadas para escalar con proveedores de atención médica de todos los tamaños, desde clínicas pequeñas hasta redes hospitalarias grandes.",
    freemiumTitle: "Freemium",
    freemiumDesc: "Perfecto para clínicas pequeñas que están comenzando",
    freemiumPrice: "$0 /mes",
    freemiumFeature1: "Hasta 2 puntos de monitoreo de temperatura",
    freemiumFeature2: "Acceso al panel web",
    freemiumFeature3: "Historial de datos de 7 días",
    freemiumFeature4: "Alertas básicas por correo electrónico",
    freemiumFeature5: "Soporte comunitario",
    premiumTitle: "Premium",
    premiumDesc: "Ideal para farmacias y centros médicos",
    premiumPrice: "$60 /mes",
    premiumFeature1: "Hasta 15 puntos de monitoreo de temperatura",
    premiumFeature2: "Alertas por correo electrónico en tiempo real",
    premiumFeature3: "Informes detallados de cumplimiento",
    premiumFeature4: "Acceso multi-usuario",
    premiumFeature5: "Alertas personalizadas",
    premiumFeature6: "Capacidades de exportación de datos",
    premiumFeature7: "Soporte prioritario",
    enterpriseTitle: "Empresarial",
    enterpriseDesc: "Soluciones escalables para redes hospitalarias o laboratorios",
    enterprisePrice: "Personalizado",
    enterpriseFeature1: "Puntos de monitoreo ilimitados",
    enterpriseFeature2: "Análisis avanzados e insights",
    enterpriseFeature3: "Integraciones personalizadas y acceso API",
    enterpriseFeature4: "Soporte Prioritario",
    enterpriseFeature5: "Permisos de usuario avanzados",
    enterpriseFeature6: "Capacitación y incorporación personalizada",
    enterpriseFeature7: "Garantías SLA",
    getStarted: "Comenzar",
    contactUs: "Contáctanos",
    pricingFooter1: "Todos los planes incluyen almacenamiento en la nube seguro, cumplimiento GDPR y actualizaciones regulares de la plataforma",
    pricingFooter2: "Para soluciones personalizadas por favor Contáctanos para precios empresariales.",
    teamBtn: "Conoce a nuestro Equipo",
    teamMember1: "Fabrizio Panta",
    teamMember2: "Axel Ordoñez",
    teamMember3: "Jean Grandez",
    teamMember4: "Oscar Espinoza",
    teamMember5: "Frezzia Espinoza",
    teamRole: "Ingeniero de Software",
    teamDesc: "Entusiasta de la tecnología y desarrollador web",
    tryDemo: "Probar Demo",
    footerTagline: "Liderando la revolución en el monitoreo de cadena de frío farmacéutica. Asegurando la seguridad de medicamentos a través de tecnología innovadora.",
    faqTitle: "Preguntas Frecuentes",
    faqInstallTitle: "¿Qué tan fácil es instalar ThermaTrace?",
    faqInstallDesc: "ThermaTrace se puede instalar en menos de 30 minutos. Nuestro equipo proporciona asistencia completa de configuración y capacitación para su personal.",
    faqComplianceTitle: "¿Cumple con los estándares de cumplimiento regulatorio?",
    faqComplianceDesc: "Sí, ThermaTrace cumple con los requisitos de cumplimiento de almacenamiento farmacéutico de la FDA, OMS y otros organismos internacionales con informes automatizados.",
    faqSupportTitle: "¿Qué tipo de soporte proporcionan?",
    faqSupportDesc: "Ofrecemos soporte técnico 24/7, actualizaciones regulares del sistema y gestión de cuentas dedicada para clientes empresariales.",
    faqIntegrationTitle: "¿Puede integrarse con sistemas existentes?",
    faqIntegrationDesc: "ThermaTrace se integra perfectamente con la mayoría de los sistemas de gestión de farmacias, EHR y sistemas de información hospitalaria.",
    faqCostTitle: "¿Cuáles son las opciones de precios?",
    faqCostDesc: "Ofrecemos planes de precios flexibles para clínicas pequeñas hasta redes hospitalarias grandes, sin contratos a largo plazo requeridos.",
    faqDataTitle: "¿Cómo se protegen mis datos?",
    faqDataDesc: "Todos los datos están encriptados y almacenados de forma segura en infraestructura en la nube compatible con HIPAA con auditorías de seguridad regulares.",
    footerLogo: "ThermaTrace",
    footerDistrictTitle: "Ubicaciones",
    footerDistrict: "Nueva York\nSan Francisco\nBoston",
    footerFollowTitle: "Síguenos",
    footerHours: "Soporte Técnico: 24/7 | Ventas: Lunes-Viernes 9am-6pm EST",
    footerContactTitle: "Contacto",
    footerContact: "Correo electrónico: contact@thermatrace.com, Teléfono: +1 (555) THERMA, Soporte: support@thermatrace.com",
    footerCopyright: "© ThermaTrace Inc. © 2025. Todos los derechos reservados."
  }
};

function changeLanguage(lang) {
  const elements = document.querySelectorAll('[data-i18n-key]');
  elements.forEach(el => {
    const key = el.getAttribute('data-i18n-key');
    if (languageData[lang] && languageData[lang][key]) {
      el.textContent = languageData[lang][key];
    }
  });
}

document.addEventListener('DOMContentLoaded', function() {
  const buttons = document.querySelectorAll('.lang-btn');
  
  buttons.forEach(button => {
    button.addEventListener('click', function() {
      const lang = this.getAttribute('data-lang');
      
      buttons.forEach(btn => btn.classList.remove('active'));
      this.classList.add('active');
      
      changeLanguage(lang);
    });
  });
});